import Head from 'next/head'
import WithAuthComponent from "../../../src/Components/Hocs/PrivateRoute";
import EditSavdo from "../../../src/Components/Pages/DashboardPages/EditSavdo";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <WithAuthComponent>
        <EditSavdo/>
      </WithAuthComponent>
    </>
  )
}
