import Head from 'next/head'
import WithAuthComponent from "../../../src/Components/Hocs/PrivateRoute";
import {useContextSelector} from "use-context-selector";
import GlobalContext from "../../../src/Context/GlobalContext/Context";
import AboutClient from "../../../src/Components/Pages/DashboardPages/AboutClient";


export default function Home() {
  const clientId = useContextSelector(GlobalContext, value => value.state.client_id)
  console.log("clientid",clientId)
  return (
    <>
      <Head>
        <title>IMPERIYA</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <WithAuthComponent>
        <AboutClient clientId={clientId}/>
      </WithAuthComponent>
    </>
  )
}
