import Head from 'next/head'
import WithAuthComponent from "../../../src/Components/Hocs/PrivateRoute";
import {useContextSelector} from "use-context-selector";
import GlobalContext from "../../../src/Context/GlobalContext/Context";
import AboutClient from "../../../src/Components/Pages/DashboardPages/AboutClient";


export default function Home() {
  const outletId = useContextSelector(GlobalContext, value => value.state.savdo_id)
  console.log(outletId)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <WithAuthComponent>
        <AboutClient/>
      </WithAuthComponent>
    </>
  )
}
