import Head from 'next/head'
import WithAuthComponent from "../../../src/Components/Hocs/PrivateRoute";
import {useContextSelector} from "use-context-selector";
import GlobalContext from "../../../src/Context/GlobalContext/Context";
import EditCashback from "../../../src/Components/Pages/DashboardPages/EditCashback";


export default function Home() {
  const cashbackId = useContextSelector(GlobalContext, value => value.state.keshbek_id)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <WithAuthComponent>
        <EditCashback cashbackId={cashbackId}/>
      </WithAuthComponent>
    </>
  )
}
