import Head from 'next/head'
import LoginPage from "../src/Components/Pages/LoginPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>IMPERIYA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage/>
    </>
  )
}
