import Head from 'next/head'
import Mijozlar from "../../src/Components/Pages/DashboardPages/Mijozlar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mijozlar/>
    </>
  )
}
