import Head from 'next/head'
import Jadval from "../../src/Components/Pages/Jadval";
import HomeDashboard from "../../src/Components/Pages/DashboardPages/Home";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeDashboard/>
    </>
  )
}
