import Head from 'next/head'
import WithAuthComponent from "../../src/Components/Hocs/PrivateRoute";
import Operatsiyalar from "../../src/Components/Pages/DashboardPages/Operatsiyalar";


export default function Home() {
    return (
        <>
            <Head>
                <title>IMPERIYA</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <WithAuthComponent>
                <Operatsiyalar/>
            </WithAuthComponent>
        </>
    )
}
