import Head from 'next/head'
import SavdoNuqtalari from "../../src/Components/Pages/DashboardPages/SavdoNuqtalari";
import WithAuthComponent from "../../src/Components/Hocs/PrivateRoute";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WithAuthComponent>
        <SavdoNuqtalari />
      </WithAuthComponent>
    </>
  )
}
